version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: scraperdb
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      PRAW_CLIENT_ID: "${CLIENT_ID}"
      PRAW_CLIENT_SECRET: "${CLIENT_SECRET}"
      PRAW_USER_AGENT: "YOUR_USER_AGENT"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: